// <auto-generated />
using C0621H2Shop.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace C0621H2Shop.Migrations
{
    [DbContext(typeof(C0621H1ShopDBContext))]
    [Migration("20210928085623_Seeding_Product_Table")]
    partial class Seeding_Product_Table
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("C0621H2Shop.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "iPhone",
                            Description = "iPhone",
                            Picture = "fas fa-mobile-alt"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Laptop",
                            Description = "Laptop",
                            Picture = "fas fa-laptop"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "PC",
                            Description = "Personal Computer",
                            Picture = "fas fa-desktop"
                        });
                });

            modelBuilder.Entity("C0621H2Shop.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Pictures")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Pictures = "~/wwwroot/images/iphone12.jpg",
                            Price = 18000000,
                            ProductName = "iPhone 12",
                            Quantity = 12
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 2,
                            Pictures = "~/wwwroot/images/laptop.jpg",
                            Price = 12000000,
                            ProductName = "Asus",
                            Quantity = 10
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 3,
                            Pictures = "~/wwwroot/images/pc.jpg",
                            Price = 13500000,
                            ProductName = "PC",
                            Quantity = 7
                        });
                });

            modelBuilder.Entity("C0621H2Shop.Entities.Product", b =>
                {
                    b.HasOne("C0621H2Shop.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
