// <auto-generated />
using C0621H2Shop.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace C0621H2Shop.Migrations
{
    [DbContext(typeof(C0621H1ShopDBContext))]
    [Migration("20210928083457_Seeding_Category_Table")]
    partial class Seeding_Category_Table
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("C0621H2Shop.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "iPhone",
                            Description = "iPhone",
                            Picture = "fas fa-mobile-alt"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Laptop",
                            Description = "Laptop",
                            Picture = "fas fa-laptop"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "PC",
                            Description = "Personal Computer",
                            Picture = "fas fa-desktop"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
